# Generated by Django 5.2 on 2025-07-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='category',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
        migrations.AddField(
            model_name='file',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is enable'),
        ),
    ]
